{"stats": {"errors": 1, "failures": 0, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 1}, "results": [{"classname": "index_test:PointTest", "name": "test_add1", "time": 0.000644683837890625, "type": "error", "errtype": "builtins.NameError", "message": "name 'y2' is not defined", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/jonastesterelli/ecc-point-addition1-jsong-pb-sf-072618/test/index_test.py\", line 9, in test_add1\n    self.assertEqual(a+b, Point(x=2, y=-5, a=5, b=7))\n  File \"/home/jonastesterelli/ecc-point-addition1-jsong-pb-sf-072618/index.ipynb\", line 39, in __add__\n    \"        # Case 1: self.x == other.x, self.y != other.y\\n\",\nNameError: name 'y2' is not defined\n"}]}